# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowV2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gbdxtools import Interface
from gbdxtools.catalog import Catalog
from gbdxtools.images.catalog_image import CatalogImage
import time
import threading
from pathlib import Path
home = str(Path.home())

class Ui_MainWindow(object):
    imageName = home + "\\Downloads\\"
    catId = []
    submitted = 0
    crop = ''  # "POLYGON((7.223781142578138 43.72999331944104,7.223781142578138 43.677872418734005,7.302058730468763 43.678865621144894,7.301372084960951 43.73148182216309,7.223781142578138 43.72999331944104))"
    order_id = ''

    def orderImage(self):
        self.catId = self.CatalogIDInput.text()
        self.order_id = gbdx.ordering.order(self.catId)
        print(self.order_id)
        self.DialogBox.append(self.CatalogIDInput.text() + " Ordered")

    def orderImageThread(self):
        if len(self.catId) == 16:
            self.DialogBox.append("Ordering")
            threading.Thread(target=self.orderImage).start()
        else:
            self.DialogBox.append("Invalid Catalog ID")

    def orderStatus(self):
        self.catId = self.CatalogIDInput.text()
        self.order_id = gbdx.ordering.order(self.catId)
        self.DialogBox.append('"' + str(gbdx.ordering.status(self.order_id)) + '"')

    def orderStatusThread(self):
        threading.Thread(target=self.orderStatus).start()

    def downloadButton(self):
        id = str(self.catId)
        c = CatalogImage(id, pansharpen=True, acomp=True)
        self.DialogBox.append(time.strftime("%H:%M:%S"))
        aoi = c.aoi(wkt=self.crop)
        self.imageName = self.imageName + self.ImageNameInput.text() + '.tif'
        image = aoi.geotiff(path=self.imageName)
        self.DialogBox.append("Finished - Image Saved In Downloads")

    def downloadButtonThread(self):
        self.catId = self.CatalogIDInput.text()
        if not self.catId:
            self.DialogBox.append("Please Enter Catalog ID")
        elif len(self.catId) != 16:
            self.DialogBox.append("Invalid Catalog ID")
        elif not self.ImageNameInput.text():
            self.DialogBox.append("Please Enter Image Name")
        else:
            self.DialogBox.append("Downloading")
            self.crop = self.CoordinatesInput.text()
            threading.Thread(target=self.downloadButton).start()

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Catalog ID label
        self.CatalogID = QtWidgets.QLabel(self.centralwidget)
        self.CatalogID.setGeometry(QtCore.QRect(10, 140, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.CatalogID.setFont(font)
        self.CatalogID.setTextFormat(QtCore.Qt.AutoText)
        self.CatalogID.setObjectName("CatalogID")

        # Catalog ID Entry
        self.CatalogIDInput = QtWidgets.QLineEdit(self.centralwidget)
        self.CatalogIDInput.setGeometry(QtCore.QRect(140, 140, 161, 21))
        self.CatalogIDInput.setObjectName("CatalogIDInput")

        # Dialog Box
        self.DialogBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.DialogBox.setGeometry(QtCore.QRect(10, 450, 781, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DialogBox.setFont(font)
        self.DialogBox.setAutoFillBackground(False)
        self.DialogBox.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.DialogBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DialogBox.setLineWidth(0)
        self.DialogBox.setDocumentTitle("")
        self.DialogBox.setSearchPaths([])
        self.DialogBox.setOpenExternalLinks(False)
        self.DialogBox.setObjectName("DialogBox")

        # Order Button
        self.OrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.OrderButton.setGeometry(QtCore.QRect(310, 390, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.OrderButton.setFont(font)
        self.OrderButton.setDefault(False)
        self.OrderButton.setFlat(False)
        self.OrderButton.setObjectName("OrderButton")
        self.OrderButton.clicked.connect(self.orderImageThread)

        # Download Button
        self.DownloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadButton.setGeometry(QtCore.QRect(500, 390, 181, 51))
        self.DownloadButton.clicked.connect(self.downloadButtonThread)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.DownloadButton.setFont(font)
        self.DownloadButton.setFlat(False)
        self.DownloadButton.setObjectName("DownloadButton")

        # Coordinates Entry Label
        self.CoordinatesEntry = QtWidgets.QLabel(self.centralwidget)
        self.CoordinatesEntry.setGeometry(QtCore.QRect(10, 180, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.CoordinatesEntry.setFont(font)
        self.CoordinatesEntry.setObjectName("CoordinatesEntry")
        self.CoordinatesInput = QtWidgets.QLineEdit(self.centralwidget)
        self.CoordinatesInput.setGeometry(QtCore.QRect(220, 180, 561, 21))
        self.CoordinatesInput.setObjectName("CoordinatesInput")

        # Image Name Entry Label
        self.ImageNameEntry = QtWidgets.QLabel(self.centralwidget)
        self.ImageNameEntry.setGeometry(QtCore.QRect(10, 220, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ImageNameEntry.setFont(font)
        self.ImageNameEntry.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ImageNameEntry.setObjectName("ImageNameEntry")

        # Image Name Entry
        self.ImageNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.ImageNameInput.setGeometry(QtCore.QRect(300, 220, 251, 21))
        self.ImageNameInput.setObjectName("ImageNameInput")

        # Background Image
        self.BackgroundImage = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundImage.setGeometry(QtCore.QRect(-4, -8, 811, 611))
        self.BackgroundImage.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BackgroundImage.setFrameShape(QtWidgets.QFrame.Panel)
        self.BackgroundImage.setText("")
        self.BackgroundImage.setPixmap(QtGui.QPixmap("light_faded_background_85547_800x600.jpg"))
        self.BackgroundImage.setObjectName("BackgroundImage")

        # Order Status Button
        self.StatusButton = QtWidgets.QPushButton(self.centralwidget)
        self.StatusButton.setGeometry(QtCore.QRect(120, 390, 181, 51))
        self.StatusButton.clicked.connect(self.orderStatusThread)

        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.StatusButton.setFont(font)
        self.StatusButton.setToolTip("")
        self.StatusButton.setAutoFillBackground(False)
        self.StatusButton.setShortcut("")
        self.StatusButton.setAutoDefault(False)
        self.StatusButton.setDefault(False)
        self.StatusButton.setFlat(False)
        self.StatusButton.setObjectName("StatusButton")

        # Title Label
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(-150, 0, 961, 121))
        self.Title.setFrameShape(QtWidgets.QFrame.HLine)
        self.Title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Title.setLineWidth(1)
        self.Title.setMidLineWidth(0)
        self.Title.setText("")
        self.Title.setPixmap(QtGui.QPixmap("../../Desktop/GBDX Images Downloader - title.png"))
        self.Title.setObjectName("Title")

        self.BackgroundImage.raise_()
        self.Title.raise_()
        self.CatalogID.raise_()
        self.CatalogIDInput.raise_()
        self.DialogBox.raise_()
        self.OrderButton.raise_()
        self.DownloadButton.raise_()
        self.CoordinatesEntry.raise_()
        self.CoordinatesInput.raise_()
        self.ImageNameEntry.raise_()
        self.ImageNameInput.raise_()
        self.StatusButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gbdx Downloader"))
        self.CatalogID.setText(_translate("MainWindow", "Enter Catalog ID:"))
        self.OrderButton.setText(_translate("MainWindow", "Order"))
        self.DownloadButton.setText(_translate("MainWindow", "Download"))
        self.CoordinatesEntry.setText(_translate("MainWindow", "Enter AOI Coordinates (wkt):"))
        self.ImageNameEntry.setText(_translate("MainWindow", "Enter Image Name (Cat ID_Area Name):"))
        self.StatusButton.setText(_translate("MainWindow", "Order Status"))


if __name__ == "__main__":
    import sys

    gbdx = Interface()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setWindowIcon(QtGui.QIcon('satellite.png'))
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
